### ISSUE TITLE
💡회원가입 추가사항이 있습니다. 부탁드립니다😄

### ISSUE THREAD

**Issue by dndbekfrl1** [HaeKang/HAMTUDY#1]
닉네임이 한글입력이 안되는 것 같습니다!
한글입력시 에러가 발생합니다.

사용자 이미지도 추가 부탁드립니다.

감사합니다😎

**Comment by dndbekfrl1** [comment]
헉 개발자님 하나 더 부탁드립니다^^;
회원가입 여기서 res.send({"state" : "성공"}); res값 회원가입한 아이디랑 닉네임이랑 사용자 이미지로 부탁 드립니다

**Comment by HaeKang** [comment]
싫어요

**Comment by HaeKang** [comment]
해결했습니다^^
